# Use official PostgreSQL image
FROM postgres:16

# Set environment variables
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres
ENV POSTGRES_DB=dj-tutorial

# Expose PostgreSQL default port
EXPOSE 5432